=== Tsuiwiki/darks-orm/test/darks.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT darks (dataSource*,useThreadLocal?,entities?,cacheGroup?,sqlMapGroup?)>

<!ELEMENT dataSource (property+,resultSet?)>
<!ATTLIST dataSource type CDATA #REQUIRED>
<!ATTLIST dataSource id CDATA #IMPLIED>
<!ATTLIST dataSource main CDATA #IMPLIED>
<!ATTLIST dataSource chainref CDATA #IMPLIED>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!ELEMENT resultSet (#PCDATA)>
<!ATTLIST resultSet type (forward|scroll) #IMPLIED>
<!ATTLIST resultSet sensitive (true|false) #IMPLIED>
<!ATTLIST resultSet concurrency (read|updatable) #IMPLIED>

<!ELEMENT entities (entity|package)*>

<!ELEMENT entity EMPTY>
<!ATTLIST entity class CDATA #REQUIRED>
<!ATTLIST entity alias CDATA #IMPLIED>

<!ELEMENT package EMPTY>
<!ATTLIST package name CDATA #REQUIRED>

<!ELEMENT useThreadLocal EMPTY>
<!ATTLIST useThreadLocal use (true|false) #REQUIRED>

<!ELEMENT sqlMapGroup (sqlMap*)>
<!ELEMENT sqlMap (#PCDATA)>

<!ELEMENT cacheGroup (appCache?,threadCache?,ehCache*)>
<!ATTLIST cacheGroup use (true|false) #REQUIRED>
<!ATTLIST cacheGroup type (auto|manual) #IMPLIED>
<!ATTLIST cacheGroup cacheId CDATA #IMPLIED>
<!ATTLIST cacheGroup synchronous (true|false) #IMPLIED>


<!ELEMENT appCache EMPTY>
<!ATTLIST appCache id CDATA #FIXED "application">
<!ATTLIST appCache strategy (Fifo|Lru|SoftRef|WeakRef) #REQUIRED>
<!ATTLIST appCache maxObject CDATA #REQUIRED>
<!ATTLIST appCache idleTime CDATA "0">
<!ATTLIST appCache liveTime CDATA "0">
<!ATTLIST appCache eternal (true|false) "true">
<!ATTLIST appCache entirety (true|false) "false">
<!ATTLIST appCache copyStrategy (field|serial|ref) #IMPLIED>


<!ELEMENT threadCache EMPTY>
<!ATTLIST threadCache id CDATA #FIXED "thread">
<!ATTLIST threadCache strategy (Fifo|Lru|SoftRef|WeakRef) #REQUIRED>
<!ATTLIST threadCache maxObject CDATA #REQUIRED>
<!ATTLIST threadCache eternal (true|false) "true">
<!ATTLIST threadCache entirety (true|false) "false">
<!ATTLIST threadCache copyStrategy (field|serial|ref) #IMPLIED>

<!ELEMENT ehCache (configPath?)>
<!ATTLIST ehCache id ID #REQUIRED>
<!ATTLIST ehCache name CDATA #IMPLIED>
<!ATTLIST ehCache maxElementsInMemory CDATA #IMPLIED>
<!ATTLIST ehCache maxElementsOnDisk CDATA #IMPLIED>
<!ATTLIST ehCache timeToIdleSeconds CDATA #IMPLIED>
<!ATTLIST ehCache timeToLiveSeconds CDATA #IMPLIED>
<!ATTLIST ehCache eternal (true|false) "true">
<!ATTLIST ehCache overflowToDisk (true|false) "false">
<!ATTLIST ehCache diskPersistent (true|false) "false">
<!ATTLIST ehCache diskExpiryThreadIntervalSeconds CDATA #IMPLIED>
<!ATTLIST ehCache memoryStoreEvictionPolicy CDATA #IMPLIED>

<!ELEMENT configPath (#PCDATA)>

=== Tsuiwiki/darks-orm/examples/darks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE darks PUBLIC "-//darks//DTD darks 3.0//EN" "darks.dtd">
<darks>

    <dataSource type="jdbc" id="jdbc" main="true">
    	<property name="driver" value="com.mysql.jdbc.Driver"></property>
    	<property name="url" value="jdbc:mysql://localhost:3306/products"></property>
    	<property name="username" value="root"></property>
    	<property name="password" value="1234"></property>
    	<property name="fetchSize" value="0"></property>
    	<property name="autoCommit" value="true"></property>
    	<resultSet type="scroll" sensitive="false" concurrency="read"></resultSet>
    </dataSource>

    <dataSource type="bonecp" id="bonecp" chainref="jdbc">
    	<property name="driver" value="com.mysql.jdbc.Driver"></property>
    	<property name="url" value="jdbc:mysql://localhost:3306/products"></property>
    	<property name="username" value="root"></property>
    	<property name="password" value="1234"></property>
    	<property name="fetchSize" value="0"></property>
    	<property name="autoCommit" value="true"></property>
    	<property name="idleConnectionTestPeriod" value="60"></property>
    	<property name="idleMaxAge" value="240"></property>
    	<property name="partitionCount" value="3"></property>
    	<property name="maxConnectionsPerPartition" value="20"></property>
    	<property name="minConnectionsPerPartition" value="5"></property>
    	<property name="acquireIncrement" value="5"></property>
    	<property name="releaseHelperThreads" value="3"></property>
    	<property name="statementsCacheSize" value="20"></property>
    	<property name="statementReleaseHelperThreads" value="3"></property>
    	<resultSet type="scroll" sensitive="false" concurrency="read"></resultSet>
    </dataSource>
    
    <useThreadLocal use="true"></useThreadLocal>
    
    <!-- 实体类配置 -->
    <entities>
		<package name="darks.orm.examples.model"/>
	</entities>
	
	<!-- 缓存配置  -->
	<cacheGroup use="false" type="auto" cacheId="application" synchronous="true">
		<appCache strategy="Lru" 
				  maxObject="50"
				  eternal="true"
				  idleTime="500"
				  liveTime="500"
				  entirety="true"
				  copyStrategy="serial"/>
		<threadCache  strategy="Lru" 
					  maxObject="50"
					  entirety="true"
					  copyStrategy="serial"/>
		<ehCache id="ehcache1"
				 maxElementsInMemory="10000"
				 eternal="false"
				 timeToIdleSeconds="0"
				 timeToLiveSeconds="0"
				 overflowToDisk="false"
				 maxElementsOnDisk="10000000"
	             diskPersistent="false"
	             diskExpiryThreadIntervalSeconds="120"
	             memoryStoreEvictionPolicy="LRU"/>
		
	</cacheGroup>
	
	<sqlMapGroup>
		<sqlMap>/sqlmap-*.xml</sqlMap>
	</sqlMapGroup>
	
	
</darks>
